[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
#target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "--cfg=web_sys_unstable_apis",
    "-C",
    "link-arg=--max-memory=4294967296"
]
#rustflags = ["--cfg=web_sys_unstable_apis"]  # When running tests
